{% set name = "opentelemetry-instrumentation-pymysql" %}
{% set version = "0.33b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-pymysql-{{ version }}.tar.gz
  sha256: 712a5622d9bcc3218b0f1d34ee57e8efe59e4d9b2e8ad09dd30be673ae795971

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.33b0
    - opentelemetry-instrumentation-dbapi ==0.33b0
    - python >=3.6
    # - pymysql ~=0.10.1
    # - opentelemetry-test ==0.24b0
    # - pymysql ~=0.10.1
    # - opentelemetry-test ==0.25b0
    # - pymysql <2
    # - opentelemetry-test-utils ==0.26b1
    # - pymysql <2
    # - opentelemetry-test-utils ==0.27b0
    # - pymysql <2
    # - opentelemetry-test-utils ==0.28b0
    # - pymysql <2
    # - opentelemetry-test-utils ==0.28b1
    # - pymysql <2
    # - opentelemetry-test-utils ==0.29b0
    # - pymysql <2
    # - opentelemetry-test-utils ==0.30b0
    # - pymysql <2
    # - opentelemetry-test-utils ==0.30b1
    # - pymysql <2
    # - opentelemetry-test-utils ==0.31b0
    # - pymysql <2
    # - opentelemetry-test-utils ==0.32b0
    # - pymysql <2
    # - opentelemetry-test-utils ==0.33b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pymysql
  summary: OpenTelemetry PyMySQL instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
